"""FIX4

Revision ID: 251bf80ee4be
Revises: 30f5d779eec3
Create Date: 2025-07-14 13:28:11.298007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251bf80ee4be'
down_revision: Union[str, Sequence[str], None] = '30f5d779eec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_verification', 'phone_number',
               existing_type=sa.CHAR(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('sms_verification', 'code',
               existing_type=sa.CHAR(length=6),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.CHAR(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.CHAR(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.CHAR(length=255),
               existing_nullable=True)
    op.alter_column('sms_verification', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.CHAR(length=6),
               existing_nullable=False)
    op.alter_column('sms_verification', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
