"""FIX2

Revision ID: 30f5d779eec3
Revises: be2aad2434f0
Create Date: 2025-07-14 12:53:43.734628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30f5d779eec3'
down_revision: Union[str, Sequence[str], None] = 'be2aad2434f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=False)
    # ### end Alembic commands ###
