"""initial

Revision ID: 838f08929180
Revises:
Create Date: 2025-07-14 08:05:27.313913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "838f08929180"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column(
            "hashed_password",
            sa.String(length=1024),
            nullable=False,
            comment="Password hash (bcrypt/argon2)",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sms_verification",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("phone_number", sa.CHAR(length=20), nullable=False),
        sa.Column("code", sa.CHAR(length=6), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего обновления",
        ),
        sa.CheckConstraint("phone_number ~ '^\\+[1-9][0-9]{1,14}$'", name="chk_e164"),
        sa.CheckConstraint("char_length(code) = 6", name="chk_code_length"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sms_not_verified",
        "sms_verification",
        ["is_verified", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sms_verification_user_id"),
        "sms_verification",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("first_name", sa.CHAR(length=128), nullable=True),
        sa.Column("last_name", sa.CHAR(length=128), nullable=True),
        sa.Column("patronymic", sa.CHAR(length=128), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("valid_vote", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "voting",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("real_quantity", sa.Integer(), nullable=False),
        sa.Column("fake_quantity", sa.Integer(), nullable=False),
        sa.Column("show_real", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "collecting", "reviewing", "accepted", "rejected", name="vote_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voting")
    op.drop_table("user")
    op.drop_index(op.f("ix_sms_verification_user_id"), table_name="sms_verification")
    op.drop_index("ix_sms_not_verified", table_name="sms_verification")
    op.drop_table("sms_verification")
    op.drop_table("admin")
    op.execute("DROP EXTENSION IF EXISTS citext")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    # ### end Alembic commands ###
