"""Fix

Revision ID: be2aad2434f0
Revises: 280842d4a4a9
Create Date: 2025-07-14 12:40:07.040911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2aad2434f0'
down_revision: Union[str, Sequence[str], None] = '280842d4a4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_not_verified'), table_name='sms_verification')
    op.create_foreign_key(None, 'sms_verification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('phone_number', sa.CHAR(length=20), nullable=False))
    op.create_unique_constraint('uq_user_phone', 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_phone', 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    op.drop_constraint(None, 'sms_verification', type_='foreignkey')
    op.create_index(op.f('ix_sms_not_verified'), 'sms_verification', ['is_verified', 'expires_at'], unique=False)
    # ### end Alembic commands ###
